name: luoyi_dart_base
description: my dart base library.
version: 1.1.0
repository: https://github.com/luoyi58624/luoyi_dart_base

environment:
  sdk: ^3.0.0

dependencies:
  # 编码和解码各种存档和压缩格式
  archive: ^3.4.10
  # 一组加密哈希函数：MD5、SHA
  crypto: ^3.0.3
  logger: ^2.1.0
  path: ^1.9.0
  uuid: ^4.3.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0